on: [push, pull_request]

name: Continuous integration

jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npx asp
